### ISSUE TITLE
Is the Wiki Getting Started correct?

### ISSUE THREAD

**Issue by sethladd** [DirectMyFile/irc.dart#25]
Hi,

I made a few changes:

* bumped the version range
* removed the "soon to be released v3" comment
* used await for

https://github.com/DirectMyFile/irc.dart/wiki/Getting-Started

Please verify.

Thanks!

**Comment by kaendfinger** [comment]
Hello! Thanks for checking it out. Only issue I see is that the await for would block the connect call. That's an issue. But other than that, it looks great.

**Comment by sethladd** [comment]
yeah. oops!

**Comment by kaendfinger** [comment]
Thanks :)
